 export const positiveReviewsArray = [
    { title: "Fantastic Experience", description: "Wonderful experience! The staff was friendly and attentive. The service was top-notch. Highly recommended!", stars: 4, image:"https://i.pinimg.com/736x/98/97/fd/9897fd7d57a93e16642b8f20419ec508.jpg" },
    { title: "Absolutely Amazing", description: "Absolutely fantastic! The ambiance, service, and amenities exceeded my expectations. Will definitely come back. 5 stars!", stars: 5, image:"https://i.pinimg.com/474x/df/02/30/df02301797468da149c8d7f0790b162d.jpg" },
    { title: "Impressive Attention to Detail", description: "Impressed with the attention to detail and excellent customer service. A solid 4-star rating for this amazing place.", stars: 4, image:"https://content.jdmagicbox.com/comp/ahmedabad/a6/079pxx79.xx79.200831115359.s9a6/catalogue/golden-fitness-the-family-gym-gurukul-ahmedabad-gyms-yyepvzo0he.jpg?clr=" },
    { title: "Hidden Gem", description: "A hidden gem! Cozy atmosphere, friendly staff, and great facilities. I'll be a regular visitor. 5 stars!", stars: 5, image:"https://content.jdmagicbox.com/comp/ahmedabad/a6/079pxx79.xx79.200831115359.s9a6/catalogue/golden-fitness-the-family-gym-gurukul-ahmedabad-gyms-yyepvzo0he.jpg?clr=" },
    { title: "Delightful Time", description: "Had a delightful time! The staff went above and beyond to make it special. 4 stars for the overall fantastic experience.", stars: 4, image:"https://content.jdmagicbox.com/comp/ahmedabad/a6/079pxx79.xx79.200831115359.s9a6/catalogue/golden-fitness-the-family-gym-gurukul-ahmedabad-gyms-yyepvzo0he.jpg?clr=" },
    { title: "Exceptional Service", description: "Exceptional service and a welcoming atmosphere. Enjoyed every moment. Solid 5-star rating for this outstanding place.", stars: 5, image:"https://content.jdmagicbox.com/comp/ahmedabad/a6/079pxx79.xx79.200831115359.s9a6/catalogue/golden-fitness-the-family-gym-gurukul-ahmedabad-gyms-yyepvzo0he.jpg?clr=" },
    { title: "Thoroughly Enjoyed", description: "Thoroughly enjoyed my visit! The facilities were well-maintained, and the staff was courteous. A solid 4 stars.", stars: 4, image:"https://content.jdmagicbox.com/comp/ahmedabad/a6/079pxx79.xx79.200831115359.s9a6/catalogue/golden-fitness-the-family-gym-gurukul-ahmedabad-gyms-yyepvzo0he.jpg?clr=" },
    { title: "Outstanding Experience", description: "Outstanding experience! From the moment I entered, I felt valued. Great service and amenities. A well-deserved 5-star rating.", stars: 5, image:"https://content.jdmagicbox.com/comp/ahmedabad/a6/079pxx79.xx79.200831115359.s9a6/catalogue/golden-fitness-the-family-gym-gurukul-ahmedabad-gyms-yyepvzo0he.jpg?clr=" },
    { title: "Charming Place", description: "Charming place with friendly staff. The service was excellent, and the ambiance was delightful. A solid 4 stars!", stars: 4, image:"https://content.jdmagicbox.com/comp/ahmedabad/a6/079pxx79.xx79.200831115359.s9a6/catalogue/golden-fitness-the-family-gym-gurukul-ahmedabad-gyms-yyepvzo0he.jpg?clr=" },
    { title: "Amazing Time", description: "Amazing time! Everything, from service to atmosphere, was exceptional. Deserves a perfect 5-star rating.", stars: 5,image:"https://content.jdmagicbox.com/comp/ahmedabad/a6/079pxx79.xx79.200831115359.s9a6/catalogue/golden-fitness-the-family-gym-gurukul-ahmedabad-gyms-yyepvzo0he.jpg?clr=" },
  ];
  
  export const introduction = "  Transform your body and achieve your fitness goals with Tarun, a certified gym trainer dedicated to helping you unlock your full potential. With Tarun's expertise, personalized training programs are tailored to your unique needs and goals, ensuring every workout session is optimized for your success. Guiding you through customized routines designed to build strength, increase endurance, and sculpt your physique, Tarun prioritizes proper exercise technique and progressive overload to ensure safe and effective workouts that deliver noticeable results.With an unwavering commitment to your success, Tarun provides comprehensive nutritional guidance to complement your training regimen. By empowering you with the knowledge and skills to make informed dietary choices, Tarun ensures your body receives the fuel it needs to perform at its best and recover efficiently.Beyond the gym floor, Tarun offers ongoing support and motivation to keep you on track towards your goals. Whether you're striving to shed excess weight, gain muscle mass, or improve overall health and wellness, Tarun's holistic approach empowers you to make positive changes to your lifestyle.Join Tarun's community and embark on a transformative journey towards a stronger, fitter, and more confident version of yourself. With Tarun as your partner in fitness, you'll not only achieve your goals but surpass them, becoming the healthiest and happiest version of yourself."

  